import org.springframework.web.servlet.support.AbstractAnnotationConfigDispatcherServletInitializer;
public class FunctionUse540 {
public void funcUse() {
AbstractAnnotationConfigDispatcherServletInitializer abstractannotationconfigdispatcherservletinitializer = new AbstractAnnotationConfigDispatcherServletInitializer();
abstractannotationconfigdispatcherservletinitializer.createRootApplicationContext();
}
}