import org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodArgumentResolver;
public class FunctionUse1720 {
public void funcUse() {
AbstractMessageConverterMethodArgumentResolver abstractmessageconvertermethodargumentresolver = new AbstractMessageConverterMethodArgumentResolver();
abstractmessageconvertermethodargumentresolver.adaptArgumentIfNecessary(null,null);
}
}