import org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodArgumentResolver;
public class FunctionUse1719 {
public void funcUse() {
AbstractMessageConverterMethodArgumentResolver abstractmessageconvertermethodargumentresolver = new AbstractMessageConverterMethodArgumentResolver();
abstractmessageconvertermethodargumentresolver.createInputMessage(null);
}
}