import org.springframework.web.servlet.config.AnnotationDrivenBeanDefinitionParser.CompositeUriComponentsContributorFactoryBean;
public class FunctionUse17 {
public void funcUse() {
CompositeUriComponentsContributorFactoryBean compositeuricomponentscontributorfactorybean = new CompositeUriComponentsContributorFactoryBean();
compositeuricomponentscontributorfactorybean.setConversionService(null);
}
}