import org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodArgumentResolver;
public class FunctionUse1716 {
public void funcUse() {
AbstractMessageConverterMethodArgumentResolver abstractmessageconvertermethodargumentresolver = new AbstractMessageConverterMethodArgumentResolver();
abstractmessageconvertermethodargumentresolver.isBindExceptionRequired(null,null);
}
}