import org.springframework.web.servlet.support.AbstractAnnotationConfigDispatcherServletInitializer;
public class FunctionUse538 {
public void funcUse() {
AbstractAnnotationConfigDispatcherServletInitializer abstractannotationconfigdispatcherservletinitializer = new AbstractAnnotationConfigDispatcherServletInitializer();
abstractannotationconfigdispatcherservletinitializer.getRootConfigClasses();
}
}