import org.springframework.web.servlet.config.AnnotationDrivenBeanDefinitionParser.CompositeUriComponentsContributorFactoryBean;
public class FunctionUse22 {
public void funcUse() {
CompositeUriComponentsContributorFactoryBean compositeuricomponentscontributorfactorybean = new CompositeUriComponentsContributorFactoryBean();
compositeuricomponentscontributorfactorybean.afterPropertiesSet();
}
}