import org.springframework.web.servlet.support.AbstractAnnotationConfigDispatcherServletInitializer;
public class FunctionUse539 {
public void funcUse() {
AbstractAnnotationConfigDispatcherServletInitializer abstractannotationconfigdispatcherservletinitializer = new AbstractAnnotationConfigDispatcherServletInitializer();
abstractannotationconfigdispatcherservletinitializer.createServletApplicationContext();
}
}