import org.springframework.web.servlet.config.AnnotationDrivenBeanDefinitionParser.CompositeUriComponentsContributorFactoryBean;
public class FunctionUse16 {
public void funcUse() {
CompositeUriComponentsContributorFactoryBean compositeuricomponentscontributorfactorybean = new CompositeUriComponentsContributorFactoryBean();
compositeuricomponentscontributorfactorybean.setHandlerAdapter(null);
}
}