import org.springframework.web.servlet.config.AnnotationDrivenBeanDefinitionParser.CompositeUriComponentsContributorFactoryBean;
public class FunctionUse21 {
public void funcUse() {
CompositeUriComponentsContributorFactoryBean compositeuricomponentscontributorfactorybean = new CompositeUriComponentsContributorFactoryBean();
compositeuricomponentscontributorfactorybean.getObject();
}
}