import org.springframework.web.servlet.config.AnnotationDrivenBeanDefinitionParser.CompositeUriComponentsContributorFactoryBean;
public class FunctionUse19 {
public void funcUse() {
CompositeUriComponentsContributorFactoryBean compositeuricomponentscontributorfactorybean = new CompositeUriComponentsContributorFactoryBean();
compositeuricomponentscontributorfactorybean.getObjectType();
}
}